# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_IoYBJxwKSWO_DlWTgM8riG9lRIEPKN

TRABAJO PRACTICO N° 1
"""

nombre = input("Por favor, ingresa tu nombre: ")

print("Hola, " + nombre + "! Bienvenido.")

lado_A = float(input("Ingresa la longitud del lado A del rectángulo: "))
lado_B = float(input("Ingresa la longitud del lado B del rectángulo: "))
# Calcular el área y el perímetro
area = lado_A * lado_B
perimetro = 2 * (lado_A + lado_B)
print(f"El área del rectángulo es: {area}")
print(f"El perímetro del rectángulo es: {perimetro}")

edad_actual = int(input("Por favor, ingresa tu edad: "))
edad_futura = edad_actual + 2
print(f"Hola! Dentro de 730 días tendrás {edad_futura} años.")

cuota_enero = 1000
factor_crecimiento = (1 + 0.02) ** 3
cuota_abril = cuota_enero * factor_crecimiento
print(f"El valor de la cuota para el mes de abril es: ${cuota_abril:.2f}")

numero1 = input("Ingresa el primer número: ")
numero2 = input("Ingresa el segundo número: ")
if numero1 > numero2:
    mayor = numero1
else:
    mayor = numero2
print(f"El número mayor entre {numero1} y {numero2} es: {mayor}")

numero = int(input("Ingresa un número entero: "))
if numero % 2 == 0:
    print(f"El número {numero} es par.")
else:
    print(f"El número {numero} es impar.")

horas_trabajadas = float(input("Ingresa el número de horas trabajadas en la semana: "))
tarifa_normal = float(input("Ingresa la tarifa por hora: "))
horas_normales = 35
if horas_trabajadas <= horas_normales:
    salario_semanal = horas_trabajadas * tarifa_normal
else:
    horas_extra = horas_trabajadas - horas_normales
    salario_semanal = (horas_normales * tarifa_normal) + (horas_extra * tarifa_normal * 1.5)
print(f"El salario neto semanal del trabajador es: ${salario_semanal:.2f}")

numeros = input("Ingresa los números enteros separados por espacios: ")
numeros_lista = list(map(int, numeros.split()))
suma_numeros = sum(numeros_lista)
print(f"La suma de los números ingresados es: {suma_numeros}")

def contar_positivos():
    numeros_str = input("Ingrese los números separados por espacios: ")
    numeros_lista = [int(x) for x in numeros_str.split()]
    contador_positivos = 0
    for numero in numeros_lista:
        if numero > 0:
            contador_positivos += 1
    print(f"En la lista ingresada hay {contador_positivos} números positivos.")
contar_positivos()

def contar_vocales(cadena):
    contador_vocales = 0
    vocales = "aeiouAEIOU"
    for caracter in cadena:
        if caracter in vocales:
            contador_vocales += 1
    return contador_vocales
texto = input("Ingrese una cadena de texto: ")
cantidad_vocales = contar_vocales(texto)
print(f"La cantidad total de vocales en la cadena es: {cantidad_vocales}")

def contar_positivos_y_total():
    numeros = []
    while True:
        numero_str = input("Ingrese un número real (o 'fin' para terminar): ")
        if numero_str.lower() == 'fin':
            break
        try:
            numero = float(numero_str)
            if numero != 0:
                numeros.append(numero)
        except ValueError:
            print("Entrada inválida. Ingrese un número real válido o 'fin' para terminar.")
    contador_positivos = sum(1 for num in numeros if num > 0)
    total_numeros = len(numeros)
    print(f"Se ingresaron un total de {total_numeros} números.")
    print(f"De los cuales, {contador_positivos} números son positivos.")
contar_positivos_y_total()

def es_palindromo(cadena):
    cadena = cadena.lower().replace(" ", "")
    return cadena == cadena[::-1]
texto = input("Ingrese una cadena de texto: ")
if es_palindromo(texto):
    print(f"La cadena '{texto}' es un palíndromo.")
else:
    print(f"La cadena '{texto}' no es un palíndromo.")

def validar_contraseña():
    contraseña_almacenada = "elsa2024"
    intentos_maximos = 3
    intentos_realizados = 0
    while intentos_realizados < intentos_maximos:
        contraseña_ingresada = input("Ingrese la contraseña: ")
        if contraseña_ingresada == contraseña_almacenada:
            print("FELICITACIONES")
            return
        intentos_realizados += 1
        if intentos_realizados < intentos_maximos:
            print(f"Contraseña incorrecta. Intento {intentos_realizados} de {intentos_maximos}.")
    print("CONTRASEÑA BLOQUEADA")
validar_contraseña()

def main():
    asignaturas = ['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua']
    notas = []
    for asignatura in asignaturas:
        nota = input(f"Ingrese la nota de {asignatura}: ")
        notas.append(nota)
    for i in range(len(asignaturas)):
        print(f"En {asignaturas[i]} sacó {notas[i]}")
if __name__ == "__main__":
    main()

def determinar_grupo(nombre, sexo):
    nombre = nombre.lower()
    sexo = sexo.lower()
    if sexo == 'mujer':
        if nombre < 'm':
            return 'A'
        else:
            return 'B'
    elif sexo == 'hombre':
        if nombre > 'n':
            return 'A'
        else:
            return 'B'
    else:
        return 'Grupo no definido'
def main():
    nombre = input("Ingrese su nombre: ")
    sexo = input("Ingrese su sexo (Hombre/Mujer): ")
    grupo = determinar_grupo(nombre, sexo)
    if grupo == 'A':
        print("Usted pertenece al Grupo A.")
    elif grupo == 'B':
        print("Usted pertenece al Grupo B.")
    else:
        print("No se pudo determinar el grupo.")
if __name__ == "__main__":
    main()

def main():
    print("Bienvenido a ML - Local de comida rápida")
    print("Seleccione el tipo de hamburguesa:")
    print("1. Hamburguesa vegetariana")
    print("2. Hamburguesa no vegetariana")
    opcion = input("Ingrese 1 o 2 para seleccionar el tipo de hamburguesa: ")

    if opcion == '1':
        tipo_hamburguesa = "vegetariana"
        print("\nIngredientes disponibles para hamburguesa vegetariana:")
        print("1. Lechuga")
        print("2. Queso")
        print("3. Tomate")
        print("4. Calabaza")
        print("5. Soja")
        ingrediente = input("Elija un ingrediente adicional (Ingrese el número): ")
        if ingrediente == '1':
            ingrediente_elegido = "Lechuga"
        elif ingrediente == '2':
            ingrediente_elegido = "Queso"
        elif ingrediente == '3':
            ingrediente_elegido = "Tomate"
        elif ingrediente == '4':
            ingrediente_elegido = "Calabaza"
        elif ingrediente == '5':
            ingrediente_elegido = "Soja"
        else:
            ingrediente_elegido = "Opción inválida"

    elif opcion == '2':
        tipo_hamburguesa = "no vegetariana"
        print("\nIngredientes disponibles para hamburguesa no vegetariana:")
        print("1. Lechuga")
        print("2. Queso")
        print("3. Tomate")
        print("4. Carne vacuna")
        print("5. Carne de pollo")
        ingrediente = input("Elija un ingrediente adicional (Ingrese el número): ")
        if ingrediente == '1':
            ingrediente_elegido = "Lechuga"
        elif ingrediente == '2':
            ingrediente_elegido = "Queso"
        elif ingrediente == '3':
            ingrediente_elegido = "Tomate"
        elif ingrediente == '4':
            ingrediente_elegido = "Carne vacuna"
        elif ingrediente == '5':
            ingrediente_elegido = "Carne de pollo"
        else:
            ingrediente_elegido = "Opción inválida"
    else:
        print("Opción inválida. Por favor seleccione 1 o 2.")
        return
    print("\nUsted ha elegido una hamburguesa", tipo_hamburguesa)
    print("Ingredientes:")
    print("- Lechuga")
    print("- Queso")
    print("- Tomate")
    print(f"- {ingrediente_elegido}")
if __name__ == "__main__":
    main()